id: I4B508492
ocr_import_info:
  timestamp: '2023-09-28T04:49:42.933278+00:00'
  batch_id: batch-af93
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-28 06:48:32.185540+00:00
last_modified: 2023-09-28 06:48:32.185548+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM4890
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM4890
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྒྱུད་སྡེ་ནས་གསུངས་པའི་ལྷ་ཚོགས་དུ་མའི་སྒྲུབ་ཐབས་ཀྱི་རིམ་པ་ཕྱོགས་གཅིག་ཏུ་བཀོད་པ་ཕན་བདེའི་འདོད་དགུ་སྟེར་བ་ཡོངས་འདུའི་ཁྲི་ཤིང་སོགས།
  languages:
  - bo
statistics:
  ocr_word_mean_confidence_index: 0.9564569955464888
  ocr_word_median_confidence_index: 0.99886775
bases:
  I1NLM4890_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM4890_001
      total_pages: 650
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM4890_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.99886775
      ocr_word_mean_confidence_index: 0.9564569955464888
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
